public class MovieTicket {
    public static String [] seatTypes = {"Regular", "Premium", "IMAX 3D"};
    public static double [] seatPrices = {300.0, 450.0, 600.0};
    public static int nightShowCharge = 15;
    private String movie;
    public String showtime;
    public String date;
    private double price;
    public String seat;
    public MovieTicket (String movie, String date, String showtime, double price) {
        this.movie = movie;
        this.showtime = showtime;
        this.date = date;
        this.price = price;
        this.seat = "Not Selected";
    }
    public void setPrice(double price) {
        this.price = price;
    }
    public double getPrice() {
        return price;
    }
    public String getMovie() {
        return movie;
    }
    public String toString() {
        return "Movie: " + movie + "\nShowtime: " + showtime + "\nDate: " + date;
    }
}

public class q75_a7c4 {
    public static void main(String[] args) {
        CinemexTicket ticket1 = new CinemexTicket("Deadpool and Wolverine", "18:30", "Action-Comedy", "July 24, 2024");
        System.out.println("Total movie ticket(s): " + CinemexTicket.getTotalTickets());
        System.out.println("1============================");
        ticket1.calculateTicketPrice();
        System.out.println("2============================");
        System.out.println(ticket1);
        System.out.println("3============================");
        System.out.println(ticket1.confirmPayment());
        System.out.println("4============================");
        System.out.println(ticket1);
        System.out.println("5============================");
        CinemexTicket ticket2 = new CinemexTicket("Twisters", "10:00", "Sci-Fi", "August 10, 2024", "Premium");
        System.out.println("Total movie ticket(s): " + CinemexTicket.getTotalTickets());
        System.out.println("6============================");
        ticket2.calculateTicketPrice();
        System.out.println("7============================");
        System.out.println(ticket2.confirmPayment());
        System.out.println("8============================");
        System.out.println(ticket2);
        System.out.println("9============================");
        System.out.println(ticket2.confirmPayment());
    }
}



/*

Design the CinemexTicket class derived from the MovieTicket Class so that the given
output is produced:
❖ The seatTypes and seatPrices arrays contain the type of the seat and its
corresponding price
❖ Night show charge (15% of ticket price) will be applicable if the time is
between 6:00 PM - 11:00 PM
❖ Unique id for a ticket is generated by:
MovieName-FirstLetterOfSeatType-TicketCount
❖ You may need to use .split() and Integer.parseInt() built-in methods


Total movie ticket(s): 1
1============================
Ticket price is calculated
successfully.
2============================
Ticket ID: Deadpool and
Wolverine-R-1
Movie: Deadpool and Wolverine
Showtime: 18:30
Date: July 24, 2024
Genre: Action-Comedy
Seat Type: Regular
Price(tk): 345.0
Status: Not Paid
3============================
Payment Successful.
4============================
Ticket ID: Deadpool and
Wolverine-R-1
Movie: Deadpool and Wolverine
Showtime: 18:30
Date: July 24, 2024
Genre: Action-Comedy
Seat Type: Regular
Price(tk): 345.0
Status: Paid
5============================
Total movie ticket(s): 2
6============================
Ticket price is calculated
successfully.
7============================
Payment Successful.
8============================
Ticket ID: Twisters-P-2
Movie: Twisters
Showtime: 10:00
Date: August 10, 2024
Genre: Sci-Fi
Seat Type: Premium
Price(tk): 450.0
Status: Paid
9============================
Ticket price is already paid!

 */